CREATE TABLE users (
  id SERIAL PRIMARY KEY, 
  name VARCHAR (50) UNIQUE NOT NULL, 
  password VARCHAR (50) NOT NULL, 
  email VARCHAR (255) UNIQUE NOT NULL,
);

ALTER TABLE users
ALTER COLUMN password TYPE
VARCHAR (255);